[app]
address = "0.0.0.0:9000"
admin_username = "admin"
admin_password = "admin"
root_url = "https://your-listmonk-service-name.onrender.com"

[db]
dsn = "postgresql://admin:wZxn1EdcMjxMWNMPEVV3DJhwjsuStqxj@dpg-d1j5h6ndiees73cltk00-a/listmonkdb"
